//************************************************************************************
//**  
//**  File name:     C:\PICDEM_Lab\flowcode\ADC_Labs\ADC_Lab1.c
//**  Generated by:  Flowcode v3.6.11.53
//**  Date:          Friday, December 04, 2009 12:14:04
//**  Licence:       Demo
//**  
//**        ***DEMO VERSION***
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F690
#define MX_EE
#define MX_EE_SIZE 256
#define MX_SPI
#define MX_SPI_BCB
#define MX_SPI_SDI 4
#define MX_SPI_SDO 7
#define MX_SPI_SCK 6
#define MX_UART
#define MX_UART_B
#define MX_UART_TX 7
#define MX_UART_RX 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_B
#define MX_I2C_SDA 4
#define MX_I2C_SCL 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 5

//Functions
#include <system.h>
#pragma CLOCK_FREQ 4000000

//Configuration data
#pragma DATA 0x2007, 0x30d5

//Internal functions
#include "C:\Program Files\Matrix Multimedia\Flowcode V3\FCD\internals.h"

//Macro function declarations
void FCM_Init_variables();


//Variable declarations
char FCV_LED_OUTPUT;




//ADC0: //Macro function declarations

void FCD_ADC0_SampleADC();
char FCD_ADC0_ReadAsByte();
short FCD_ADC0_ReadAsInt();

//Supplementary defines




//ADC0: //Macro implementations


void FCD_ADC0_SampleADC()
{
	//This is from the FCD file...
	//set up ADC conversion
	char old_tris, cnt;
	#define MX_ADC_SAMP_TIME 40
	adcon1 = 0x20;

	//find appropriate bit
	#if (10 == 0)
	  #define MX_ADC_TRIS_REG  trisa
	  #define MX_ADC_TRIS_MSK  0x01
	  ansel = 0x01;
	#endif
	#if (10 == 1)
	  #define MX_ADC_TRIS_REG  trisa
	  #define MX_ADC_TRIS_MSK  0x02
	  ansel = 0x02;
	#endif
	#if (10 == 2)
	  #define MX_ADC_TRIS_REG  trisa
	  #define MX_ADC_TRIS_MSK  0x04
	  ansel = 0x04;
	#endif
	#if (10 == 3)
	  #define MX_ADC_TRIS_REG  trisa
	  #define MX_ADC_TRIS_MSK  0x10
	  ansel = 0x08;
	#endif
	#if (10 == 4)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x01
	  ansel = 0x10;
	#endif
	#if (10 == 5)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x02
	  ansel = 0x20;
	#endif
	#if (10 == 6)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x04
	  ansel = 0x40;
	#endif
	#if (10 == 7)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x08
	  ansel = 0x80;
	#endif
	#if (10 == 8)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x40
	  anselh = 0x01;
	#endif
	#if (10 == 9)
	  #define MX_ADC_TRIS_REG  trisc
	  #define MX_ADC_TRIS_MSK  0x80
	  anselh = 0x02;
	#endif
	#if (10 == 10)
	  #define MX_ADC_TRIS_REG  trisb
	  #define MX_ADC_TRIS_MSK  0x10
	  anselh = 0x04;
	#endif
	#if (10 == 11)
	  #define MX_ADC_TRIS_REG  trisb
	  #define MX_ADC_TRIS_MSK  0x20
	  anselh = 0x08;
	#endif

	//sanity check
	#ifndef MX_ADC_TRIS_REG
	  #pragma error ADC conversion code error - please contact technical support
	#endif
	 
	//store old tris value, and set the i/o pin as an input
	old_tris = MX_ADC_TRIS_REG;
	MX_ADC_TRIS_REG = MX_ADC_TRIS_REG | MX_ADC_TRIS_MSK;
	 
	//turn ADC on
	adcon0 = 0x01 | (10 << 2);

	//wait the acquisition time
	cnt = 0;
	while (cnt < MX_ADC_SAMP_TIME) cnt++;
	 
	//begin conversion and wait until it has finished
	adcon0 = adcon0 | 0x02;
	while (adcon0 & 0x02);

	//restore old tris value, and reset adc registers
	MX_ADC_TRIS_REG = old_tris;
	ansel = 0;
	anselh = 0;
	adcon0 = 0x00;
	#undef MX_ADC_TRIS_REG
	#undef MX_ADC_TRIS_MSK
	#undef MX_ADC_SAMP_TIME

}

char FCD_ADC0_ReadAsByte()
{
	//This is from the FCD file...
	return adresh;

}

short FCD_ADC0_ReadAsInt()
{
	//This is from the FCD file...
	short iRetVal;
	iRetVal = (adresh << 2);
	iRetVal += (adresl >> 6);
	return (iRetVal);

}

//Macro implementations

void FCM_Init_variables()
{
	//Initializes variables used in this application
	
	//Calculation
	//Calculation:
	//  LED_Output = 0b00000000
	FCV_LED_OUTPUT = 0b00000000;
	

}

//Supplementary implementations


void main()
{
	
	//Initialisation
	ansel = 0;
anselh = 0;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//Initialize
	//Call Macro: Init_variables
	FCM_Init_variables();


	//Loop
	//Loop: While 1
	while (1)
	{
		//Get_Inputs
		//Call Component Macro: ADC(0)::SampleADC
		FCD_ADC0_SampleADC();


		//Decide
		//Call Component Macro: LED_Output=ADC(0)::ReadAsByte
		FCV_LED_OUTPUT = FCD_ADC0_ReadAsByte();


		//Output
		//Output: LED_Output -> PORT C
		trisc = 0x00;
		portc = FCV_LED_OUTPUT;


	}


	mainendloop: goto mainendloop;
}

void interrupt(void)
{
}



