//************************************************************************************
//**  
//**  File name:     C:\PICDEM_Lab\flowcode\Comparator_Labs\Comparator_Lab3\solution\Comparator_Lab3.c
//**  Generated by:  Flowcode v3.6.11.53
//**  Date:          Thursday, December 03, 2009 16:39:58
//**  Licence:       Demo
//**  
//**        ***DEMO VERSION***
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F690
#define MX_EE
#define MX_EE_SIZE 256
#define MX_SPI
#define MX_SPI_BCB
#define MX_SPI_SDI 4
#define MX_SPI_SDO 7
#define MX_SPI_SCK 6
#define MX_UART
#define MX_UART_B
#define MX_UART_TX 7
#define MX_UART_RX 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_B
#define MX_I2C_SDA 4
#define MX_I2C_SCL 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 5

//Functions
#include <system.h>
#pragma CLOCK_FREQ 4000000

//Configuration data
#pragma DATA 0x2007, 0x30d5

//Internal functions
#include "C:\Program Files\Matrix Multimedia\Flowcode V3\FCD\internals.h"

//Macro function declarations
void FCM_Init_Peripherals();
void FCM_TMR0_ISR();


//Variable declarations
char FCV_COUNTER;
char FCV_LED_OUTPUT;



//Supplementary defines


//Macro implementations

void FCM_Init_Peripherals()
{
	
	//Init_C2_TMR0
	//C Code:
	//Comparator 2 Initialization
	trisc.TRISC4 = 0; //set the RC4/C2OUT pin as output
	cm2con0 = 0b10100001; //configure Comparator 2
	                     //Turn on Comparator 2
	//Only the first 4 lines of C code will be compiled in this free version of Flowcode.
	//                     //Enable Comparator 2 output on the
	//                     //C2OUT pin
	//                     //Connect Comparator non-inverting
	//                     //reference to RC0/C2IN+ pin
	//                      //Connect Comparator inverting reference
	//                     //to RC1/C12IN1- pin
	////TMR0 Clock Source Initialization
	////Make RA2/T0CKI pin a digital input
	//trisa.TRISA2 = 1;
	//ansel.ANS2 = 0;



	//Initialize_Variables
	//Calculation:
	//  LED_Output = 0b00000000
	//  counter = 0
	FCV_LED_OUTPUT = 0b00000000;
	FCV_COUNTER = 0;
	

}

void FCM_TMR0_ISR()
{
	//This is the interrupt service routine for the Timer0 overflow interrupt. The counter variable incremented with the main flowchart software loop is first assigned to the LED_Output variable then cleared before returning from the interrupt.
	
	//Assign counter to LED_Output
	//Calculation:
	//  LED_Output = counter << 4
	//  counter = 0
	FCV_LED_OUTPUT = FCV_COUNTER << 4;
	FCV_COUNTER = 0;
	

}

//Supplementary implementations


void main()
{
	
	//Initialisation
	ansel = 0;
anselh = 0;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//Initialize
	//Call Macro: Init_Peripherals
	FCM_Init_Peripherals();


	//Interrupt
	//Interrupt: Enable TMR0 Overflow
	option_reg.T0CS=1;
	option_reg.T0SE=0;
	option_reg = (option_reg & 0xF0) | 0x01;
	intcon.GIE=1;
	intcon.T0IE=1;


	//Loop
	//Loop: While 1
	while (1)
	{
		//Decide
		//Calculation:
		//  counter = counter + 1
		FCV_COUNTER = FCV_COUNTER + 1;
		

		//Do_Outputs
		//Output: LED_Output -> PORT B
		trisb = 0x00;
		portb = FCV_LED_OUTPUT;


		//Timing
		//Delay: 1 ms
		delay_ms(1);


	}


	mainendloop: goto mainendloop;
}

void interrupt(void)
{
	if (intcon & (1 << T0IF))
	{
		FCM_TMR0_ISR();
		clear_bit(intcon, T0IF);
	}


}



