//************************************************************************************
//**  
//**  File name:     C:\PICDEM_Lab\flowcode\GPIO_Labs\GPIO_Lab5\solution\GPIO_Lab5.c
//**  Generated by:  Flowcode v3.6.11.53
//**  Date:          Thursday, December 03, 2009 15:40:03
//**  Licence:       Demo
//**  
//**        ***DEMO VERSION***
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F690
#define MX_EE
#define MX_EE_SIZE 256
#define MX_SPI
#define MX_SPI_BCB
#define MX_SPI_SDI 4
#define MX_SPI_SDO 7
#define MX_SPI_SCK 6
#define MX_UART
#define MX_UART_B
#define MX_UART_TX 7
#define MX_UART_RX 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_B
#define MX_I2C_SDA 4
#define MX_I2C_SCL 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 5

//Functions
#include <system.h>
#pragma CLOCK_FREQ 4000000

//Configuration data
#pragma DATA 0x2007, 0x30d5

//Internal functions
#include "C:\Program Files\Matrix Multimedia\Flowcode V3\FCD\internals.h"

//Macro function declarations
void FCM_Shift();
void FCM_INT_ISR();


//Variable declarations
char FCV_LED_OUTPUT;
char FCV_DIRECTION;



//Supplementary defines


//Macro implementations

void FCM_Shift()
{
	//This macro is used to shift contents of the LED_Output variable by one bit position either Left or Right depending on the state of the direction variable. Prior to any shift, the condition that will result in LED_Output = 0 is checked.
	
	//Decision
	//Decision: direction = 1?
	if (FCV_DIRECTION == 1)
	{
		//Check if LSb of LED_Output is set
		//Decision: LED_Output = 0b00000001?
		if (FCV_LED_OUTPUT == 0b00000001)
		{
			//Set MSb in LED_Output
			//Calculation:
			//  LED_Output = 0b10000000
			FCV_LED_OUTPUT = 0b10000000;
			

		} else {
			//Shift LED_Output data right
			//Calculation:
			//  LED_Output = LED_Output >> 1
			FCV_LED_OUTPUT = FCV_LED_OUTPUT >> 1;
			

		}


	} else {
		//Check if MSb of LED_Output is set
		//Decision: LED_Output = 0b10000000?
		if (FCV_LED_OUTPUT == 0b10000000)
		{
			//Set LSb in LED_Output 
			//Calculation:
			//  LED_Output = 0b00000001
			FCV_LED_OUTPUT = 0b00000001;
			

		} else {
			//Shift LED_Output data left
			//Calculation:
			//  LED_Output = LED_Output << 1
			FCV_LED_OUTPUT = FCV_LED_OUTPUT << 1;
			

		}


	}


	//Check LED_Output for zero condition
	//Decision: LED_Output = 0b00000000?
	if (FCV_LED_OUTPUT == 0b00000000)
	{
		//Set LSb in LED_Output
		//Calculation:
		//  LED_Output = 0b00000001
		FCV_LED_OUTPUT = 0b00000001;
		

	}


}

void FCM_INT_ISR()
{
	//This macro services the external edge-triggered interrupt. If the pushbutton connected transitions from LOW-to-HIGH triggering an interrupt, the direction bit variable is toggled. 
	
	//Toggle direction variable
	//Calculation:
	//  direction = direction XOR 0b00000001
	FCV_DIRECTION = FCV_DIRECTION ^ 0b00000001;
	

}

//Supplementary implementations


void main()
{
	
	//Initialisation
	ansel = 0;
anselh = 0;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//PB_Interrupt
	//Interrupt: Enable RB0/INT
	option_reg.INTEDG=1;
	intcon.GIE=1;
	intcon.INTE=1;


	//Initialize
	//Calculation:
	//  LED_Output = 0b00000000
	//  direction = 0
	FCV_LED_OUTPUT = 0b00000000;
	FCV_DIRECTION = 0;
	

	//Loop
	//Loop: While 1
	while (1)
	{
		//Decide
		//Call Macro: Shift
		FCM_Shift();


		//Do_Outputs
		//Output: LED_Output -> PORT C
		trisc = 0x00;
		portc = FCV_LED_OUTPUT;


		//Delay
		//Delay: 1 s
		delay_s(1);


	}


	mainendloop: goto mainendloop;
}

void interrupt(void)
{
	if (intcon & (1 << INTF))
	{
		FCM_INT_ISR();
		clear_bit(intcon, INTF);
	}


}



