//************************************************************************************
//**  
//**  File name:     C:\PICDEM_Lab\flowcode\GPIO_Labs\GPIO_Lab3\solution\GPIO_Lab3.c
//**  Generated by:  Flowcode v3.6.11.53
//**  Date:          Thursday, December 03, 2009 13:43:43
//**  Licence:       Demo
//**  
//**        ***DEMO VERSION***
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F690
#define MX_EE
#define MX_EE_SIZE 256
#define MX_SPI
#define MX_SPI_BCB
#define MX_SPI_SDI 4
#define MX_SPI_SDO 7
#define MX_SPI_SCK 6
#define MX_UART
#define MX_UART_B
#define MX_UART_TX 7
#define MX_UART_RX 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_B
#define MX_I2C_SDA 4
#define MX_I2C_SCL 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 5

//Functions
#include <system.h>
#pragma CLOCK_FREQ 4000000

//Configuration data
#pragma DATA 0x2007, 0x30d5

//Internal functions
#include "C:\Program Files\Matrix Multimedia\Flowcode V3\FCD\internals.h"

//Macro function declarations
void FCM_Shift_Rt();


//Variable declarations
char FCV_LED_OUTPUT;



//Supplementary defines


//Macro implementations

void FCM_Shift_Rt()
{
	//This macro first checks the contents of the LED_Output variable to see if the LSb is set to 1. If so, the variable is re-intialized to 0b10000000 setting the MSb. Otherwise, the contents of LED_Output are shifted to the right by one bit position. 
	
	//Check LSb of LED_Output
	//Decision: LED_Output = 0b00000001?
	if (FCV_LED_OUTPUT == 0b00000001)
	{
		//Reinitialize LED_Output
		//Calculation:
		//  LED_Output = 0b10000000
		FCV_LED_OUTPUT = 0b10000000;
		

	} else {
		//Shift LED_Output data right
		//Calculation:
		//  LED_Output = LED_Output >> 1
		FCV_LED_OUTPUT = FCV_LED_OUTPUT >> 1;
		

	}


}

//Supplementary implementations


void main()
{
	
	//Initialisation
	ansel = 0;
anselh = 0;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//Initialize
	//Calculation:
	//  LED_Output = 0b10000000
	FCV_LED_OUTPUT = 0b10000000;
	

	//Loop
	//Loop: While 1
	while (1)
	{
		//Decide
		//Call Macro: Shift_Rt
		FCM_Shift_Rt();


		//Do_Outputs
		//Output: LED_Output -> PORT C
		trisc = 0x00;
		portc = FCV_LED_OUTPUT;


		//Timing
		//Delay: 1 s
		delay_s(1);


	}


	mainendloop: goto mainendloop;
}

void interrupt(void)
{
}



