//************************************************************************************
//**  
//**  File name:     C:\PICDEM_Lab\flowcode\Comparator_Labs\Comparator_Lab2\solution\Comparator_Lab2.c
//**  Generated by:  Flowcode v3.6.11.53
//**  Date:          Thursday, December 03, 2009 15:58:01
//**  Licence:       Demo
//**  
//**        ***DEMO VERSION***
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//************************************************************************************


#define MX_PIC

//Defines for microcontroller
#define P16F690
#define MX_EE
#define MX_EE_SIZE 256
#define MX_SPI
#define MX_SPI_BCB
#define MX_SPI_SDI 4
#define MX_SPI_SDO 7
#define MX_SPI_SCK 6
#define MX_UART
#define MX_UART_B
#define MX_UART_TX 7
#define MX_UART_RX 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_B
#define MX_I2C_SDA 4
#define MX_I2C_SCL 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_TRIS1 trisc
#define MX_PWM_1 5

//Functions
#include <system.h>
#pragma CLOCK_FREQ 4000000

//Configuration data
#pragma DATA 0x2007, 0x30d5

//Internal functions
#include "C:\Program Files\Matrix Multimedia\Flowcode V3\FCD\internals.h"

//Macro function declarations
void FCM_Initialize_Comparator1_CVref();


//Variable declarations
char FCV_LED_OUTPUT;



//Supplementary defines


//Macro implementations

void FCM_Initialize_Comparator1_CVref()
{
	
	//Initialize_Comparator1_CVref
	//C Code:
	trisa = 0b11111011; //configures PORTA pin direction
	cm1con0 = 0b10100100; // configures comparator 1 with CVREF
	                       //as non-inverting input to
	                       //Comparator 1

	//Only the first 4 lines of C code will be compiled in this free version of Flowcode.
	//vrcon = 0b10101100; //Initializes CVREF to 2.5V


}

//Supplementary implementations


void main()
{
	
	//Initialisation
	ansel = 0;
anselh = 0;


	//Interrupt initialisation code
	option_reg = 0xC0;


	//Initialize
	//Call Macro: Initialize_Comparator1_CVref
	FCM_Initialize_Comparator1_CVref();


	//Loop
	//Loop: While 1
	while (1)
	{
	}


	mainendloop: goto mainendloop;
}

void interrupt(void)
{
}



